New Logo: Nextdoor
Automattic/social-logos pull request #119
Opened 2023-05-05 19:33 UTC by pablinos

This adds the logo for Nextdoor. I've copied the procedure carried out to add Mastodon in #115. Building the assets, and bumping the version and adding a changelog entry.

2023-05-05 19:35 UTC, pablinos commented on svg-min-react/nextdoor.svg
I'm not sure if this is what we want as the logos have turned out as just black circles! I notice that a similar thing happened with Mastodon though.

2023-05-08 11:32 UTC, jeherve commented on sources/svg/nextdoor.svg
I think we've sticked to black for previous logos. I think we should do the same here.

2023-05-09 22:00 UTC, pablinos commented on sources/svg/nextdoor.svg
Ah yes, I'll fix that. Maybe the colours are part of the problem.

2023-05-09 22:22 UTC, pablinos commented
I think I've managed to fix it. The SVG wasn't outlined properly. Would you mind taking another look when you get a chance please @jeherve?

2023-05-10 08:02 UTC, jeherve requested changes
I think you may have to update the lock file as well? Otherwise, this seems good to go!

2023-05-10 15:19 UTC, renjunl reviewed
Thank you for the effort in integrating ShareKit. I am the software engineer from Nextdoor Partnership team. Looking forward to collaborating with you in the future.

2023-05-10 15:57 UTC, pablinos commented
> I think you may have to update the lock file as well? Otherwise, this seems good to go!

Oof, sorry, I've fixed that now, thanks @jeherve!

2023-05-10 15:58 UTC, pablinos commented
> Thank you for the effort in integrating ShareKit. I am the software engineer from Nextdoor Partnership team. Looking forward to collaborating with you in the future.

Great, nice to meet you @renjunl! This change allows us to use the icon in our other code bases. I'll let you know as we raise more PRs

2023-05-10 15:59 UTC, jeherve approved these changes

2023-05-10 16:54 UTC, renjunl commented
> > Thank you for the effort in integrating ShareKit. I am the software engineer from Nextdoor Partnership team. Looking forward to collaborating with you in the future.
> 
> Great, nice to meet you @renjunl! This change allows us to use the icon in our other code bases. I'll let you know as we raise more PRs

Thank you, can you tag @kevinchai0 kchai@nextdoor.com  in the future PRs related to Nextdoor too? Thanks.

2023-05-24 14:00 UTC, jeherve commented
> I think I've managed to fix it. The SVG wasn't outlined properly.

when you get the chance, could you walk me through the steps you followed to do that, or take a look at the Mastodon and Titktok alt logos in this repo and see if the same fix can be applied to those logos too? That may allow us to move forward with #117.

Thank you!

2023-06-15 15:05 UTC, jeherve approved these changes
I've rebased things, it should be good to go now! Merging.

2023-06-15 15:05 UTC, merged

2023-06-19 19:33 UTC, pablinos commented
Thanks @jeherve!

> when you get the chance, could you walk me through the steps you followed to do that, or take a look at the Mastodon and Titktok alt logos in this repo and see if the same fix can be applied to those logos too? 

It looks like they're working ok now, so I assume you sorted it, but the problem with this one was that the 'n' wasn't cut out from the background, so I outlined it. We can do the same to any other problematic ones.

2023-07-13 11:55 UTC, mikeritter commented
Thanks guys!